name: build

on:
  push:
  pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL 'https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz' | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

      - name: checkout the branch
        uses: actions/checkout@v4

      - name: print lean and lake versions
        run: |
          lean --version
          lake --version

      - name: ensure all modules are included
        run: |
          lake exe mk_all || :

      - name: get cache
        run: lake exe cache get

      - name: prune ProofWidgets .lake
        run: |
          # The ProofWidgets release contains not just the `.js` (which we need in order to build)
          # but also `.oleans`, which may have been built with the wrong toolchain.
          # This removes them.
          # See discussion at https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/nightly-testing/near/411225235
          rm -rf .lake/packages/proofwidgets/.lake/build/lib
          rm -rf .lake/packages/proofwidgets/.lake/build/ir
          lake build ProofWidgets

      - name: build project
        run: lake build

      - name: build blueprint and copy to `docs/blueprint`
        uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20231201
          run: |
            apk update
            apk add --update make py3-pip git pkgconfig graphviz graphviz-dev gcc musl-dev
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git config --global --add safe.directory "$(pwd)"
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip requests wheel
            pip install pygraphviz --global-option=build_ext --global-option="-L/usr/lib/graphviz/" --global-option="-R/usr/lib/graphviz/"
            pip install leanblueprint
            leanblueprint pdf
            mkdir docs
            cp blueprint/print/print.pdf docs/blueprint.pdf
            leanblueprint web
            cp -r blueprint/web docs/blueprint

      - name: check blueprint declarations
        run: lake exe checkdecls blueprint/lean_decls

      - name: cache mathlib docs
        uses: actions/cache@v4
        with:
          path: |
            .lake/build/doc/init
            .lake/build/doc/lake
            .lake/build/doc/lean
            .lake/build/doc/std
            .lake/build/doc/mathlib
            .lake/build/doc/declarations
            !.lake/build/doc/declarations/declaration-data-algebrainlean*
          key: mathlibdoc-${{ hashfiles('lake-manifest.json') }}
          restore-keys: |
            mathlibdoc-

      - name: build documentation
        run: lake -R -Kenv=dev build AlgebraInLean:docs

      - name: copy docs to `docs/docs`
        run: |
          sudo chown -R runner docs
          cp -r .lake/build/doc docs/docs

      - name: upload docs & blueprint artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-all
    if: github.ref_type == 'branch' && github.ref_name == 'master'
    steps:
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
