name: build-strict

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lake-build:
    runs-on: ubuntu-latest
    steps:

      # Below steps are adapted from Mathlib
      # https://github.com/leanprover-community/mathlib4/blob/master/.github/workflows/lean4checker.yml
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "${GITHUB_PATH}"

      - name: checkout the branch
        uses: actions/checkout@v4

      - name: print lean and lake versions
        run: |
          lean --version
          lake --version

      - name: confirm all modules are included
        run: lake exe mk_all --check

      - name: confirm exercises are up-to-date
        run: |
          python3 ./scripts/mk_exercises.py
          git add -- Exercises
          git diff --cached --quiet -- Exercises

      - name: get cache
        run: lake exe cache get

      - name: prune ProofWidgets .lake
        run: |
          # The ProofWidgets release contains not just the `.js` (which we need in order to build)
          # but also `.oleans`, which may have been built with the wrong toolchain.
          # This removes them.
          # See discussion at https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/nightly-testing/near/411225235
          rm -rf .lake/packages/proofwidgets/.lake/build/lib
          rm -rf .lake/packages/proofwidgets/.lake/build/ir
          lake build ProofWidgets

      - name: build project
        run: lake build --wfail
